//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapPosition
    {
        public System.Guid Id { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.Guid SoldierId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Soldier Soldier { get; set; }
    }
}
