//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soldier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soldier()
        {
            this.MapPositions = new HashSet<MapPosition>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int RankId { get; set; }
        public int CountryId { get; set; }
        public string TrainingInfo { get; set; }
        public System.Guid SensorId { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapPosition> MapPositions { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
